### PR TITLE
Improve create tabs with pages demo

### PR DESCRIPTION
**Pull request by aBnormaLz**
Remove unnecessary pages variable that created a div around the components and modify the code accordingly

### CODE REVIEW

**Comment by aBnormaLz** [comment]
Should I fix the SonarQube errors on the lines I didn't really touch? :D

**Comment by tomivirkki** [comment]
Hi and thanks for the contribution.

Maybe the wrapping `div` can be useful for someone who might want to, for example, add unified padding or background color for all content. wdyt?

Screenshot 2020-08-12 at 14 54 30

**Comment by aBnormaLz** [comment]
Well actually that's true but as I saw the example codes tend to be the minimal code you need to get the Component working. Maybe it's better to have an example with the div and without the div so we have the minimal approach and also the developers can see how to configure something across the tab-contents. How does it sound? :)

**Comment by tomivirkki** [comment]
It would be kind of an overkill to have two separate examples for the same thing.
From component hierarchy point of view, it's still better organized to only have Tabs and the content wrapper on one level (static, non-changing) and the dynamically changing pages (one at a time ideally) inside the content wrapper:

- tabs
- content
  - page1 or page2 or page3

..instead of having the tabs and the arbitrary set of content on the same level:

- tabs
- page1
- page2
- page3

One thing I would change in the demo though is that the content wrapper would only include one view at a time. So that the tab change listener would only do:

```
pages.removeAll();
pages.add(tabsToPages.get(event.getSelectedTab()));
```

Currently, the example is overly complex as it has extra logic for changing the visibility of each page while keeping them all in the DOM at the same time.

**Comment by aBnormaLz** [comment]
I modified the commit accordingly

**Comment by tomivirkki** [comment]
The demo changes lgtm, but the [test that uses the demo](https://github.com/vaadin/vaadin-tabs-flow/blob/master/vaadin-tabs-flow-integration-tests/src/test/java/com/vaadin/flow/component/tabs/tests/TabsIT.java#L39) should be updated also so that the build would pass.

**Comment by aBnormaLz** [comment]
I didn't see those tests, I think they are fixed now

**Review by tomivirkki — APPROVED** [review]

**Pull request merged**
